CRITICAL - 2021-08-09 00:44:34 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/check/{"...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/check/{"...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:45:17 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/check/po...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/check/po...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:45:40 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/check/po...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/check/po...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:45:46 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/check/po...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/check/po...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:46:02 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:46:08 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:46:37 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:48:56 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 00:49:31 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 01:04:31 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 01:04:35 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard...')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 01:05:04 --> syntax error, unexpected '<', expecting end of file
#0 C:\xampp\htdocs\test\system\Router\Router.php(169): CodeIgniter\Router\Router->autoRoute('donate/postcard')
#1 C:\xampp\htdocs\test\system\CodeIgniter.php(809): CodeIgniter\Router\Router->handle('donate/postcard')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(389): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-08-09 01:07:17 --> file_get_contents(https://disease.sh/v3/covid-19/countries/Vietnam): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\test\app\Controllers\Query.php(18): file_get_contents('https://disease...')
#2 C:\xampp\htdocs\test\system\CodeIgniter.php(928): App\Controllers\Query->covid()
#3 C:\xampp\htdocs\test\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Query))
#4 C:\xampp\htdocs\test\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\test\public\index.php(38): CodeIgniter\CodeIgniter->run()
#6 {main}
